openapi: 3.0.0
x-bc-implicit-head: true
x-bc-implicit-options: true
x-bc-throttle-key: $bf_capture_account_id
x-bc-upstream: 'http://backend_server'
info:
  title: Brightcove Interactivity API リファレンス
  description: |- 
    videocloud でインタラクティビティ データにアクセスするための API です。API リクエストをテストするには <a href="/getting-started/concepts-testing-tools-brightcove-apis.html" target="_blank">API テストツール</a>を使用することが出来ます.

    API の機能に関する詳細なガイドについては、 **[一般ドキュメント](/interactivity/index.html)**を参照して下さい。

    **Base URL**: https://interactivity.api.brightcove.com
  version: 1.0.115-e554f8e
  x-bc-studio: interactivity
servers:
  - url: 'https://interactivity.api.brightcove.com' 
paths:
  '/v1/accounts/{アカウント_id}/projects':
    get:
      summary: 特定アカウントの全プロジェクトの取得。
      description: 特定アカウントの全プロジェクトを取得します。デフォルトでは最初の10件のプロジェクトを返します。
      tags:
        - Projects
      operationId: GetProjects
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
    post:
      summary: 特定アカウント用のプロジェクトを作成。
      description: 特定アカウント用のプロジェクトを作成。
      tags:
        - Projects
      operationId: CreateProject
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/projects/counts':
    get:
      summary: 特定アカウントのプロジェクト数を取得。
      description: 特定アカウントのプロジェクト数を取得。
      tags:
        - Projects
      operationId: GetProjectCount
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
  '/v1/accounts/{account_id}/projects/{id}':
    get:
      summary: 特定アカウントから特定のプロジェクトを取得。
      description: 特定アカウントから特定のプロジェクトを取得。
      tags:
        - Projects
      operationId: GetProject
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
    patch:
      summary: 特定アカウントの特定のプロジェクトを更新。
      description: 特定アカウントの特定のプロジェクトを更新。
      tags:
        - Projects
      operationId: UpdateProject
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/projects/{id}/{soft_delete}':
    delete:
      summary: 特定アカウントの特定のプロジェクトを削除。
      description: 特定アカウントの特定のプロジェクトを削除します。デフォルトではソフト削除を実行します。ハード削除を行うにはリクエストボディを使用してください。
      tags:
        - Projects
      operationId: DeleteProject
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/projects/{id}/annotations':
    get:
      summary: 特定プロジェクトの全アノテーションを取得。
      description: 特定プロジェクトの全アノテーションを取得。
      tags:
        - Project Annotations
      operationId: GetProjectAnnotations
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
    post:
      summary: プロジェクト用のアノテーションを作成。
      description: プロジェクト用のアノテーションを作成。
      tags:
        - Project Annotations
      operationId: CreateAnnotation
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/projects/{id}/annotations/{annotation_id}':
    get:
      summary: 特定プロジェクトの特定のアノテーションを取得。
      description: 特定プロジェクトの特定のアノテーションを取得。
      tags:
        - Project Annotations
      operationId: GetAnnotation
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
    patch:
      summary: アノテーションの更新。
      description: アノテーションの更新。
      tags:
        - Project Annotations
      operationId: UpdateAnnotation
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
    delete:
      summary: アノテーションの削除。
      description: アノテーションの削除。
      tags:
        - Project Annotations
      operationId: DeleteAnnotation
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/templates':
    get:
      summary: 特定アカウントの全テンプレートを取得。
      description: 特定アカウントの全テンプレートを取得します。デフォルトでは最初の10件のテンプレートを返します。
      tags:
        - Templates
      operationId: GetTemplates
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
    post:
      summary: アカウント用のテンプレートを作成。
      description: アカウント用のテンプレートを作成。
      tags:
        - Templates
      operationId: CreateTemplate
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/templates/counts':
    get:
      summary: 特定アカウントのテンプレート数を取得。
      description: 特定アカウントのテンプレート数を取得。
      tags:
        - Templates
      operationId: GetTemplateCount
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
  '/v1/accounts/{account_id}/templates/{id}':
    get:
      summary: アカウントの特定のテンプレートを取得。
      description: アカウントの特定のテンプレートを取得。
      tags:
        - Templates
      operationId: GetTemplate
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
    patch:
      summary: テンプレートを更新。
      description: テンプレートを更新。
      tags:
        - Templates
      operationId: UpdateTemplate
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all 
  '/v1/accounts/{account_id}/templates/{id}/{soft_delete}':
    delete:
      summary: テンプレートの削除。
      description: テンプレートを削除します。デフォルトではソフト削除を実行します。ハード削除を行うにはリクエストボディを使用してください。
      tags:
        - Templates
      operationId: DeleteTemplate
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/templates/{id}/annotations':
    get:
      summary: 特定テンプレートの全アノテーションを取得。
      description: 特定テンプレートの全アノテーションを取得。
      tags:
        - Template Annotations
      operationId: GetTemplateAnnotations
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
    post:
      summary: テンプレート用のアノテーションを作成。
      description: テンプレート用のアノテーションを作成。
      tags:
        - Template Annotations
      operationId: CreateTemplateAnnotation
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/templates/{id}/annotations/{annotation_id}':
    get:
      summary: 特定テンプレートの特定のアノテーションを取得。
      description: 特定テンプレートの特定のアノテーションを取得。
      tags:
        - Template Annotations
      operationId: GetTemplateAnnotationById
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
    patch:
      summary: アノテーションを更新。
      description: アノテーションを更新。
      tags:
        - Template Annotations
      operationId: UpdateTemplateAnnotationById
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
    delete:
      summary: アノテーションの削除。
      description: アノテーションの削除。
      tags:
        - Template Annotations
      operationId: DeleteTemplateAnnotationById
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/experiences':
    get:
      summary: 特定アカウントの全エクスペリエンスを取得。
      description: 特定アカウントの全エクスペリエンスを取得。
      tags:
        - Experiences
      operationId: GetExperiences
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
    post:
      summary: アカウント用のエクスペリエンスを作成。
      description: アカウント用のエクスペリエンスを作成。
      tags:
        - Experiences
      operationId: CreateExperience
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/experiences/counts':
    get:
      summary: 特定アカウントのエクスペリエンス数を取得。
      description: 特定アカウントのエクスペリエンス数を取得。
      tags:
        - Experiences
      operationId: GetExperienceCount
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
  '/v1/accounts/{account_id}/experiences/{id}':
    get:
      summary: アカウントの特定のエクスペリエンスを取得。
      description: アカウントの特定のエクスペリエンスを取得。
      tags:
        - Experiences
      operationId: GetExperience
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
    patch:
      summary: エクスペリエンスを更新。
      description: エクスペリエンスを更新。
      tags:
        - Experiences
      operationId: UpdateExperience
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all   
  '/v1/accounts/{account_id}/experiences/{id}/{soft_delete}': 
    delete:
      summary: エクスペリエンスを削除。
      description: エクスペリエンスを削除します。デフォルトではソフト削除を実行します。ハード削除を行うにはリクエストボディを使用してください。
      tags:
        - Experiences
      operationId: DeleteExperience
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/experiences/{id}/scorm_download':
    get:
      summary: SCORM ダウンロードを取得。
      description: エクスペリエンス用の SCORM zip ファイルを取得。
      tags:
        - Experiences
      operationId: GetExperienceScormDownload
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
  '/v1/accounts/{account_id}/folders':
    get:
      summary: 特定アカウントの全フォルダを取得。
      description: 特定アカウントの全フォルダを取得。
      tags:
        - Folders
      operationId: GetFolders
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
    post:
      summary: アカウント用のフォルダを作成。
      description: アカウント用のフォルダを作成。
      tags:
        - Folders
      operationId: CreateFolder
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/folders/{id}':
    get:
      summary: アカウントの特定のフォルダを取得。
      description: アカウントの特定のフォルダを取得。
      tags:
        - Folders
      operationId: GetFolder
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
    patch:
      summary: フォルダの名前を変更。
      description: フォルダの名前を変更。
      tags:
        - Folders
      operationId: RenameFolder
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
    delete:
      summary: フォルダを削除。
      description: フォルダを削除。
      tags:
        - Folders
      operationId: DeleteFolder
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/folders/{id}/contents':
    get:
      summary: アカウントの特定のフォルダの内容を取得。
      description: アカウントの特定のフォルダの内容を取得。
      tags:
        - Folders
      operationId: GetFolderContents
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/folders/{id}/contents/counts':
    get:
      summary: アカウントの特定のフォルダ内のコンテンツ項目数を取得。
      description: アカウントの特定のフォルダ内のコンテンツ項目数を取得。
      tags:
        - Folders
      operationId: GetFolderContentsCounts
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/folders/{id}/contents/{content_id}':
    put:
      summary: コンテンツ項目をフォルダに移動。
      description: アカウントの特定のフォルダにコンテンツ項目を移動。
      tags:
        - Folders
      operationId: MoveContentToFolder
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
    delete:
      summary: フォルダからコンテンツ項目を削除。
      description: アカウントの特定のフォルダからコンテンツ項目を削除。
      tags:
        - Folders
      operationId: RemoveContentFromFolder
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/reports/gradebook/summary':
    get:
      summary: 成績表サマリーレポートを取得。
      description: ユーザーIDごとにグループ化された正解数を取得。
      tags:
        - Reports
      operationId: GetGradeBookSummary
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/reports/gradebook/users/answers':
    get:
      summary: 成績表ユーザー回答詳細レポートを取得。
      description: ユーザーが提出した回答を取得。
      tags:
        - Reports
      operationId: GetGradeBookDetails
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/reports/quiz/actions':
    get:
      summary: クイズアクションレポートを取得。
      description: プロジェクトごとにグループ化された回答済み質問の数を取得。
      tags:
        - Reports
      operationId: GetQuizActions
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/reports/quiz/project/summary':
    get:
      summary: クイズプロジェクトサマリーレポートを取得。
      description: 質問および回答ごとにグループ化されたユニークな提出回答数を取得。
      tags:
        - Reports
      operationId: GetQuizActionsSummary
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
components:
  securitySchemes:
    BC_OAuth2:
      type: oauth2
      description: 'Brightcove OAuth API. See the [support documentation](https://support.brightcove.com/oauth-api) or [Getting Access Tokens](https://support.brightcove.com/oauth-api-sample-get-access-token) to learn more'
      flows:
        clientCredentials:
          tokenUrl: 'https://oauth.brightcove.com/v4/access_token'
          scopes:
            video-cloud/interactivity/read: Read
            video-cloud/interactivity/all: All